### ISSUE TITLE
Patch submitted?

### ISSUE THREAD

**Issue by ffes** [nickgravgaard/ElasticTabstopsForScintilla#1]
Did you or David submit the Scintilla patch to the Scintilla team?
If so, I couldn't find it in any of their sf.net trackers. What was/is the result?

If not, do you have plans to do so?
If not, is there a special reason for not submitting?

**Comment by nick-gravgaard** [comment]
*Edit:* In August 2014 I worked with Neil to get explicit tabstops into Scintilla 3.5.0 (http://sourceforge.net/p/scintilla/code/ci/3f3ae214c626d7276aee35a14d1ffa1ad848c9cd/).

For more information see the [README](https://github.com/nickgravgaard/ElasticTabstopsForScintilla/blob/master/README.md).
